# Generated by Django 4.2.10 on 2024-03-24 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("UG-SY", "UG - SY"),
                            ("UG-TY", "UG - TY"),
                            ("UG-FY", "UG - FY"),
                            ("PG-SY", "PG - SY"),
                        ],
                        max_length=10,
                    ),
                ),
                ("prn_number", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
