# Generated by Django 4.2.10 on 2024-03-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("venue", models.TextField(max_length=1000)),
                ("theme", models.TextField(max_length=1000)),
                ("games", models.TextField(max_length=1000)),
                ("cards", models.TextField(max_length=1000)),
                ("gifts", models.TextField(max_length=1000)),
                ("food", models.TextField(max_length=1000)),
            ],
        ),
    ]
