# Generated by Django 4.2.10 on 2024-03-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_packages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=2000)),
            ],
        ),
    ]
